### ISSUE TITLE
Support the auto combination of numeric variables

### ISSUE THREAD

**Issue by seonghobae** [seonghobae/kaefa#17]
# Details
https://github.com/seonghobae/kaefa/blob/da6bf9df8acbdbd32f00c4c44b6f7e84b6efa8f5/R/utils.R#L3-L68

In current, ```kaefa:::.covdataFixedEffectComb``` returns a list which includes the classified categorical variable candidates for fixed and random effect.

So, In currently, Support the auto combination of numeric variables required.

Especially, L9 to L16 was incomplete.

https://github.com/seonghobae/kaefa/blob/da6bf9df8acbdbd32f00c4c44b6f7e84b6efa8f5/R/utils.R#L9-L16

# Todo

- [x] Check is that a unique numeric variable which one of the covariance data frame.

- [x] Add return outcomes which one is real numeric variable (ex. age). -- If False Positive, That doesn't matter in estimation. Because that's just a trial, not harm.

- [x] Link with combination function in internal.
https://github.com/seonghobae/kaefa/blob/da6bf9df8acbdbd32f00c4c44b6f7e84b6efa8f5/R/newEngine.R#L75-L85
https://github.com/seonghobae/kaefa/blob/da6bf9df8acbdbd32f00c4c44b6f7e84b6efa8f5/R/kaefa.R#L383
